### Numpy

In [1]:
import numpy as np


In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
array_a = np.array([1, 2, 3, 4])

In [4]:
array_b = np.array([0, .5, 1, 1.5, 2, 2.5])

In [6]:
array_a[0]

1

In [8]:
array_b[-1]

2.5

In [9]:
array_a[:2]

array([1, 2])

In [10]:
array_a.dtype

dtype('int32')

In [11]:
array_b.dtype

dtype('float64')

In [12]:
empty_array = np.array([])

In [13]:
empty_array.dtype

dtype('float64')

In [14]:
np.array([1, 2, 3, 4, 5], dtype= np.float_)

array([1., 2., 3., 4., 5.])

In [15]:
np.array([1, 2, 3], dtype = np.int8)

array([1, 2, 3], dtype=int8)

In [16]:
array_c = np.array(["ada", "lovelace"])

In [17]:
array_c.dtype

dtype('<U8')

### Dimensions and Shapes

In [18]:
m_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [19]:
m_array.shape

(2, 3)

In [20]:
m_array.ndim

2

In [22]:
deneme = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [23]:
deneme.ndim

3

In [25]:
deneme.size

12

In [26]:
deneme.shape

(2, 2, 3)

#### Indexing and slicing

In [27]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

In [28]:
my_array[0][2]

3

In [29]:
my_array[0 : 2]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
my_array[2] = 99

In [31]:
my_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

In [35]:
my_array2 = np.arange(1,11)
my_array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
my_array2.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [38]:
np.arange(1,10.1, 2)

array([1., 3., 5., 7., 9.])

In [42]:
np.zeros((2,3,3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [43]:
np.ones((2,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
my_array3 = np.random.random((3,2))

In [50]:
my_array3

array([[0.95048812, 0.55949147],
       [0.7662479 , 0.53505502],
       [0.35275325, 0.3168309 ]])

In [53]:
np.random.randint(50,100, (3,3))

array([[69, 75, 71],
       [57, 60, 86],
       [80, 64, 69]])

In [54]:
np.linspace(2.5, 4.5, num=6)

array([2.5, 2.9, 3.3, 3.7, 4.1, 4.5])

In [55]:
np.any([-1, 3, 6])

True

In [56]:
np.all(0, -1)

False

In [58]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [67]:
np.concatenate((my_array, my_array) , axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

### statistics

In [77]:
array1= np.arange(0,10)
array1 = array1.reshape(2,5)

In [78]:
array1.sum()

45

In [79]:
array1.mean()

4.5

In [80]:
array1.std()

2.8722813232690143

In [81]:
array1.var()

8.25

In [82]:
array1.sum(axis=1)

array([10, 35])

In [83]:
array1 +10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Boolean arrays

In [86]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [88]:
a[[True, False, True, True]]

array([0, 2, 3])

In [89]:
a >=2 

array([False, False,  True,  True])

In [90]:
a[a>=2]

array([2, 3])

In [91]:
a.mean()

1.5

In [92]:
a[ a > a.mean() ]

array([2, 3])

In [94]:
a[ ~(a > a.mean()) ]

array([0, 1])

mupy içerisinde and or not yerine bitwise karşılıkları kullanılır

In [95]:
a[(a==0) | (a == 1)]

array([0, 1])

In [96]:
a[(a<=2) & (a % 2 ==0)]

array([0, 2])

100'e kadar rastgele tamsayılardan oluşan, 3,3 bir matris oluşturun

In [103]:
arr = np.random.randint(100, size=(3,3))
arr

array([[36, 27, 13],
       [86, 85, 48],
       [44, 29, 32]])

30dan büyük olanları boolean yöntemi ile fitreleyin

In [104]:
arr[arr>30]

array([36, 86, 85, 48, 44, 32])

In [105]:
boolean = arr > 30
arr[boolean]

array([36, 86, 85, 48, 44, 32])

In [107]:
arr2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1 = arr2.reshape(5,2)
array_2 = arr2.reshape(2,5)

In [108]:
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [109]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [110]:
np.dot(array_1, array_2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [112]:
np.transpose(array_1)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [113]:
array_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [115]:
import sys
sys.getsizeof(10)

28

In [118]:
sys.getsizeof(1000**100)

160

In [122]:
np.dtype(int).itemsize

4

In [120]:
np.dtype(np.int8).itemsize

1

In [123]:
np.dtype(float).itemsize

8

In [124]:
sys.getsizeof([])

56

In [125]:
sys.getsizeof([1, 2, 3])

88

In [143]:
my_list = list( range(10000))

In [144]:
my_arrange = np.arange(10000)

In [146]:
%time np.sum(my_arrange ** 2)

CPU times: total: 0 ns
Wall time: 996 µs


-1724114088

In [147]:
%time sum([number ** 2 for number in my_list])

CPU times: total: 0 ns
Wall time: 2.99 ms


333283335000